### ISSUE TITLE
Configuration file name is misspelled in README

### ISSUE THREAD

**Issue by ntorresd** [GuanZihan/GradMetapopulation#3]
Just a small correction to the README. The configuration file name is misspelled in there:
https://github.com/GuanZihan/GradMetapopulation/blob/3c5e83b3b42db709c0a2f80fc0384ea45b985457/README.md?plain=1#L7-L9
It should read instead:
```bash
conda env create -f environment.yml
```

**Comment by GuanZihan** [comment]
typo fixed
