### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ntorresd** [GuanZihan/GradMetapopulation#5]
When running:
```bash
python main.py -st MA -j -d 0 --seed 1234 -m meta -di bogota -date "0_moving" 
```
I got the following error:
```
AssertionError: Torch not compiled with CUDA enabled
```
This may prevent the tool to be usable in non-NVIDIA machines, so I suggest adding an option to avoid the need for pytorch to rely on CUDA. I'm aware this may affect performance, but it would enable usability in different frameworks.

**Comment by GuanZihan** [comment]
Thanks for the suggestion. Now the code supports CPU. You can just set -d cpu.
